// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestoAPI.Data;

#nullable disable

namespace TestoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230208192926_testcases")]
    partial class testcases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestoAPI.Models.CaseStudies", b =>
                {
                    b.Property<int>("CaseStudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseStudyId"));

                    b.Property<DateTime>("CaseCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideLines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questionnaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartingPoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseStudyId");

                    b.ToTable("CaseStudies");
                });

            modelBuilder.Entity("TestoAPI.Models.TestResults", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<float?>("AverageTimeOnTask")
                        .HasColumnType("real");

                    b.Property<int>("CaseStudyId")
                        .HasColumnType("int");

                    b.Property<int?>("Errors")
                        .HasColumnType("int");

                    b.Property<string>("ScrollDepthRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TaskSucessRate")
                        .HasColumnType("real");

                    b.Property<int?>("TimeElapsed")
                        .HasColumnType("int");

                    b.Property<int?>("UserClicks")
                        .HasColumnType("int");

                    b.Property<string>("VisitedSites")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultId");

                    b.HasIndex("CaseStudyId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("TestoAPI.Models.TestResults", b =>
                {
                    b.HasOne("TestoAPI.Models.CaseStudies", "CaseStudy")
                        .WithMany()
                        .HasForeignKey("CaseStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
