// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestoAPI.Data;

#nullable disable

namespace TestoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestoDashboard.Models.CaseStudies", b =>
                {
                    b.Property<int>("CaseStudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseStudyId"));

                    b.Property<DateTime>("CaseCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questionnaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isTestCaseDone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseStudyId");

                    b.ToTable("CaseStudies");
                });

            modelBuilder.Entity("TestoDashboard.Models.TestResults", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<float?>("AverageTimeOnTask")
                        .HasColumnType("real");

                    b.Property<int>("CaseStudyId")
                        .HasColumnType("int");

                    b.Property<int?>("Errors")
                        .HasColumnType("int");

                    b.Property<string>("ScrollDepthRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TaskSucessRate")
                        .HasColumnType("real");

                    b.Property<int?>("TimeElapsed")
                        .HasColumnType("int");

                    b.Property<int?>("UserClicks")
                        .HasColumnType("int");

                    b.Property<string>("VisitedSites")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultId");

                    b.HasIndex("CaseStudyId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TestoDashboard.Models.TestResults", b =>
                {
                    b.HasOne("TestoDashboard.Models.CaseStudies", "CaseStudy")
                        .WithMany()
                        .HasForeignKey("CaseStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
